name: CI/CD Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurez Docker pour se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construisez et poussez l'image Docker
      - name: Build and push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USER/bot-discord:latest .
          docker push $DOCKER_USER/bot-discord:latest
